services:
  live-meet-app:
    build:
      context: .
      dockerfile: ./app.Dockerfile
    container_name: live-meet-app
    restart: unless-stopped  # Choose either 'always' or 'unless-stopped'
    ports:
      - '5022:3000'
    environment:
      LIVEKIT_URL: ${LIVEKIT_URL}
      LIVEKIT_API_KEY: ${LIVEKIT_API_KEY}
      LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET}
      NEXT_PUBLIC_LIVEKIT_URL: ${NEXT_PUBLIC_LIVEKIT_URL}
      DATABASE_URL: ${DATABASE_URL}
      # NextAuth Configuration
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}

      # Google OAuth Configuration
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    command: >
      sh -c "npx prisma migrate deploy &&
             npm start"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/api/health/ready"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    networks:
      app-net: {}
    # Resource limits optimized for 8GB RAM, 2 vCPU server
    deploy:
      resources:
        limits:
          cpus: '1.5'      # Max 1.5 vCPUs for app
          memory: 3G       # Max 3GB RAM for app
        reservations:
          cpus: '0.5'      # Guaranteed 0.5 vCPU
          memory: 1.5G     # Guaranteed 1.5GB RAM

networks:
  app-net:
    external: true
    name: "live-meet-net"