apiVersion: 1

datasources:
  - name: PostgreSQL Monitoring
    type: postgres
    uid: postgres-monitoring-ds  # Fixed UID to prevent changes
    access: proxy
    url: postgres-monitoring:5432
    database: monitoring_db
    user: monitoring
    secureJsonData:
      password: monitoring123
    jsonData:
      sslmode: disable
      postgresVersion: 1500  # PostgreSQL 15
      timescaledb: false
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    isDefault: true
    editable: true
    version: 1
